### ISSUE TITLE
Pre publication checklist

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/xspl_power_analyser#15]
- [x] Footer to credit us including twitter handles
- [x] github icon to go to repo
- [x] Add DOI (reserve on ORDA)
- [x] Make responsive to mobile
- [x] Push to Sheffield shiny.

**Comment by annakrystalli** [comment]
All complete now! Have a look at the app and let me know if it's ok. I'm gonna tidy the repo a bit but we should be good to go very soon!
